repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.5.0
    hooks:
    -   id: pylint
        additional_dependencies: ['packaging', 'requests']
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.13.1
    hooks:
    -   id: gitlint
